package com.riotApi

fun championId(id:Int): String {
    when(id){
     266 -> return "Aatrox"
     412 -> return "Thresh" 
     23 -> return "Tryndamere" 
     79 -> return "Gragas" 
     69 -> return "Cassiopeia" 
     136 -> return "Aurelion Sol" 
     13 -> return "Ryze" 
     78 -> return "Poppy" 
     14 -> return "Sion" 
     1 -> return "Annie" 
     202 -> return "Jhin" 
     43 -> return "Karma" 
     111 -> return "Nautilus" 
     240 -> return "Kled" 
     99 -> return "Lux" 
     103 -> return "Ahri" 
     2 -> return "Olaf" 
     112 -> return "Viktor" 
     34 -> return "Anivia" 
     27 -> return "Singed" 
     86 -> return "Garen" 
     127 -> return "Lissandra" 
     57 -> return "Maokai" 
     25 -> return "Morgana" 
     28 -> return "Evelynn" 
     105 -> return "Fizz" 
     74 -> return "Heimerdinger" 
     238 -> return "Zed" 
     68 -> return "Rumble" 
     82 -> return "Mordekaiser" 
     37 -> return "Sona" 
     96 -> return "Kog'Maw" 
     55 -> return "Katarina" 
     117 -> return "Lulu" 
     22 -> return "Ashe" 
     30 -> return "Karthus" 
     12 -> return "Alistar" 
     122 -> return "Darius" 
     67 -> return "Vayne" 
     110 -> return "Varus" 
     77 -> return "Udyr" 
     89 -> return "Leona" 
     126 -> return "Jayce" 
     134 -> return "Syndra" 
     80 -> return "Pantheon" 
     92 -> return "Riven" 
     121 -> return "KhaZix"
     42 -> return "Corki" 
     268 -> return "Azir" 
     51 -> return "Caitlyn" 
     76 -> return "Nidalee" 
     85 -> return "Kennen" 
     3 -> return "Galio" 
     45 -> return "Veigar" 
     432 -> return "Bard" 
     150 -> return "Gnar" 
     90 -> return "Malzahar" 
     104 -> return "Graves" 
     254 -> return "Vi" 
     10 -> return "Kayle" 
     39 -> return "Irelia" 
     64 -> return "Lee Sin" 
     420 -> return "Illaoi" 
     60 -> return "Elise" 
     106 -> return "Volibear" 
     20 -> return "Nunu" 
     4 -> return "Twisted Fate" 
     24 -> return "Jax" 
     102 -> return "Shyvana" 
     429 -> return "Kalista" 
     36 -> return "Dr. Mundo" 
     427 -> return "Ivern" 
     131 -> return "Diana" 
     223 -> return "Tahm Kench" 
     63 -> return "Brand" 
     113 -> return "Sejuani" 
     8 -> return "Vladimir" 
     154 -> return "Zac" 
     421 -> return "Rek'Sai" 
     133 -> return "Quinn" 
     84 -> return "Akali" 
     163 -> return "Taliyah" 
     18 -> return "Tristana" 
     120 -> return "Hecarim" 
     15 -> return "Sivir" 
     236 -> return "Lucian" 
     107 -> return "Rengar" 
     19 -> return "Warwick" 
     72 -> return "Skarner" 
     54 -> return "Malphite" 
     157 -> return "Yasuo" 
     101 -> return "Xerath" 
     17 -> return "Teemo" 
     75 -> return "Nasus" 
     58 -> return "Renekton" 
     119 -> return "Draven" 
     35 -> return "Shaco" 
     50 -> return "Swain" 
     91 -> return "Talon" 
     40 -> return "Janna" 
     115 -> return "Ziggs" 
     245 -> return "Ekko" 
     61 -> return "Orianna" 
     114 -> return "Fiora" 
     9 -> return "Fiddlesticks" 
     31 -> return "Cho'Gath" 
     33 -> return "Rammus" 
     7 -> return "LeBlanc" 
     16 -> return "Soraka" 
     26 -> return "Zilean" 
     56 -> return "Nocturne" 
     222 -> return "Jinx" 
     83 -> return "Yorick" 
     6 -> return "Urgot" 
     203 -> return "Kindred" 
     21 -> return "Miss Fortune" 
     62 -> return "Wukong" 
     53 -> return "Blitzcrank" 
     98 -> return "Shen" 
     201 -> return "Braum" 
     5 -> return "Xin Zhao" 
     29 -> return "Twitch" 
     11 -> return "Master Yi" 
     44 -> return "Taric" 
     32 -> return "Amumu" 
     41 -> return "Gangplank" 
     48 -> return "Trundle" 
     38 -> return "Kassadin" 
     161 -> return "Vel'Koz" 
     143 -> return "Zyra" 
     267 -> return "Nami" 
     59 -> return "Jarvan IV" 
     81 -> return "Ezreal"
     235->return "Senna"
     145->return "Kaisa"
     498->return "Xayah"
     887->return "Gwen"
     234->return "Viego"
     246->return "qiyana"
        else->println("Can't find champion for id=$id")
    }
 return "NO DATA"
}